Update dask-image to version 0.6.0
AnacondaRecipes/dask-image-feedstock pull request #1
Opened 2021-10-28 20:50 UTC by varlackc

1. check the upstream
https://github.com/dask/dask-image/tree/v0.6.0

2. check the pinnings
https://github.com/dask/dask-image/blob/v0.6.0/setup.py
https://github.com/dask/dask-image/blob/v0.6.0/environment_doc.yml

Python 3.5 is specified on the setup.py file
https://github.com/dask/dask-image/blob/v0.6.0/setup.py#L74

3. check changelogs
https://github.com/dask/dask-image/releases/tag/v0.6.0

The changes mentioned were new features improvements and bug fixes and 

New Features
- GPU support for ndmorph subpackage: binary morphological functions (`#157`)

Improvements
- Improve imread performance: reduced overhead of pim.open calls when reading from image sequence (`#182`)

Bug Fixes
- dask-image imread v0.5.0 not working with dask distributed Client & napari (`#194`)
- Not able to map actual image name with dask_image.imread (#200, fixed by `#182`)
- affine_transform: Remove inconsistencies with ndimage implementation `#205`

4. additional research
https://github.com/conda-forge/dask-image-feedstock/issues

there are no open issues at the time of the review

5. verify dev_url
dev_url: https://github.com/dask/dask-image

6. verify doc_url
doc_url: https://dask-image.readthedocs.io/

7. verify that pip is in the test section
8. verify the test section
9. additional tests

In order to test the `dask-image` package version `0.6.0` the following command was used:
`conda build dask-image-feedstock --test` 
The test result was the following:
`All tests passed`

Since there are no packages depending on `dask-image 0.6.0` no import test were conducted.

Based on the research findings and on the test results we can conclude that it is safe to update `dask-image` to version `0.6.0`

2021-10-29 07:23 UTC, katietz requested changes

2021-10-29 07:23 UTC, katietz commented on recipe/meta.yaml
> +    - python >=3.5
No pinning of python in "build" section!

2021-10-29 16:42 UTC, varlackc commented on recipe/meta.yaml
> +    - python >=3.5
The issues in the requirements build were corrected:
https://github.com/AnacondaRecipes/dask-image-feedstock/blob/update_to_0.6.0/recipe/meta.yaml#L23

2021-10-29 16:46 UTC, varlackc commented on recipe/meta.yaml
The pinnings for python in the requirements build section were modified.

2021-11-02 08:13 UTC, katietz approved these changes
LGTM, thanks

2021-11-03 10:33 UTC, katietz approved these changes
Thanks

2021-12-10 20:20 UTC, merged